In [1]:
import pandas as pd
import numpy as np

In [15]:
df=pd.read_csv('data/homeprices.csv')
df

town  area   price
0   monroe township  2600  550000
1   monroe township  3000  565000
2   monroe township  3200  610000
3   monroe township  3600  680000
4   monroe township  4000  725000
5      west windsor  2600  585000
6      west windsor  2800  615000
7      west windsor  3300  650000
8      west windsor  3600  710000
9       robinsville  2600  575000
10      robinsville  2900  600000
11      robinsville  3100  620000
12      robinsville  3600  695000

# Pandas Dummy Variable method

In [5]:
dummies=pd.get_dummies(df['town'])
merged=pd.concat([df,dummies],axis=1)
merged

town  area   price  monroe township  robinsville  west windsor
0   monroe township  2600  550000                1            0             0
1   monroe township  3000  565000                1            0             0
2   monroe township  3200  610000                1            0             0
3   monroe township  3600  680000                1            0             0
4   monroe township  4000  725000                1            0             0
5      west windsor  2600  585000                0            0             1
6      west windsor  2800  615000                0            0             1
7      west windsor  3300  650000                0            0             1
8      west windsor  3600  710000                0            0             1
9       robinsville  2600  575000                0            1             0
10      robinsville  2900  600000                0            1             0
11      robinsville  3100  620000                0            1             0
12      robinsville  3600  695000                0            1             0

In [6]:
final=merged.drop(['town','monroe township'],axis=1)
final

area   price  robinsville  west windsor
0   2600  550000            0             0
1   3000  565000            0             0
2   3200  610000            0             0
3   3600  680000            0             0
4   4000  725000            0             0
5   2600  585000            0             1
6   2800  615000            0             1
7   3300  650000            0             1
8   3600  710000            0             1
9   2600  575000            1             0
10  2900  600000            1             0
11  3100  620000            1             0
12  3600  695000            1             0

In [7]:
from sklearn.linear_model import LinearRegression
model=LinearRegression()
model.fit(final.drop('price',axis=1),final['price'])

LinearRegression()

In [8]:
model.predict([[2800,1,0]])

array([590775.63964739])

In [9]:
model.predict([[3400,0,1]])

array([681241.6684584])

In [10]:
model.score(final.drop('price',axis=1),final['price'])

0.9573929037221872

# Using OneHotEncoder

In [11]:
from sklearn.preprocessing import OneHotEncoder
from sklearn.compose import ColumnTransformer

In [16]:
x=df.drop('price',axis=1)
ct=ColumnTransformer([('town',OneHotEncoder(),[0])],remainder='passthrough')
x=ct.fit_transform(x)
x=x[:,1:]
x

array([[0.0e+00, 0.0e+00, 2.6e+03],
       [0.0e+00, 0.0e+00, 3.0e+03],
       [0.0e+00, 0.0e+00, 3.2e+03],
       [0.0e+00, 0.0e+00, 3.6e+03],
       [0.0e+00, 0.0e+00, 4.0e+03],
       [0.0e+00, 1.0e+00, 2.6e+03],
       [0.0e+00, 1.0e+00, 2.8e+03],
       [0.0e+00, 1.0e+00, 3.3e+03],
       [0.0e+00, 1.0e+00, 3.6e+03],
       [1.0e+00, 0.0e+00, 2.6e+03],
       [1.0e+00, 0.0e+00, 2.9e+03],
       [1.0e+00, 0.0e+00, 3.1e+03],
       [1.0e+00, 0.0e+00, 3.6e+03]])

In [17]:
y=df['price']

In [18]:
model.fit(x,y)

LinearRegression()

In [21]:
model.predict([[1,0,2800]])

array([590775.63964739])

In [20]:
model.predict([[0,1,3400]])

array([681241.66845839])

# Solving Practice Problem

In [22]:
df=pd.read_csv('data/carprices.csv')
df

Car Model  Mileage  Sell Price($)  Age(yrs)
0                  BMW X5    69000          18000         6
1                  BMW X5    35000          34000         3
2                  BMW X5    57000          26100         5
3                  BMW X5    22500          40000         2
4                  BMW X5    46000          31500         4
5                 Audi A5    59000          29400         5
6                 Audi A5    52000          32000         5
7                 Audi A5    72000          19300         6
8                 Audi A5    91000          12000         8
9   Mercedez Benz C class    67000          22000         6
10  Mercedez Benz C class    83000          20000         7
11  Mercedez Benz C class    79000          21000         7
12  Mercedez Benz C class    59000          33000         5

In [27]:
dummies=pd.get_dummies(df['Car Model'],drop_first=True)
final_df=pd.concat([df.drop('Car Model',axis=1),dummies],axis=1)
final_df

Mileage  Sell Price($)  Age(yrs)  BMW X5  Mercedez Benz C class
0     69000          18000         6       1                      0
1     35000          34000         3       1                      0
2     57000          26100         5       1                      0
3     22500          40000         2       1                      0
4     46000          31500         4       1                      0
5     59000          29400         5       0                      0
6     52000          32000         5       0                      0
7     72000          19300         6       0                      0
8     91000          12000         8       0                      0
9     67000          22000         6       0                      1
10    83000          20000         7       0                      1
11    79000          21000         7       0                      1
12    59000          33000         5       0                      1

In [32]:
x=final_df.drop('Sell Price($)',axis=1)
y=final_df['Sell Price($)']
model.fit(x,y)

LinearRegression()

In [30]:
model.predict([[45000,4,0,1]])

array([36991.31721061])

In [31]:
model.predict([[86000,7,1,0]])

array([11080.74313219])

In [33]:
model.score(x,y)

0.9417050937281082