In [1]:
import pandas as pd
import numpy as np

In [11]:
df=pd.read_csv('data/homeprices.csv')
df

area  bedrooms  age   price
0  2600       3.0   20  550000
1  3000       4.0   15  565000
2  3200       NaN   18  610000
3  3600       3.0   30  595000
4  4000       5.0    8  760000
5  4100       6.0    8  810000

In [13]:
import math
df['bedrooms']=df['bedrooms'].fillna(math.floor(df['bedrooms'].median()))
df

area  bedrooms  age   price
0  2600       3.0   20  550000
1  3000       4.0   15  565000
2  3200       4.0   18  610000
3  3600       3.0   30  595000
4  4000       5.0    8  760000
5  4100       6.0    8  810000

In [14]:
from sklearn.linear_model import LinearRegression
model=LinearRegression()
model.fit(df.drop('price',axis=1),df['price'])

LinearRegression()

In [17]:
model.predict([[3000,3,40]])

array([498408.25158031])

# Solving Practice Problem

In [32]:
df=pd.read_csv('data/hiring.csv')
df

experience  test_score(out of 10)  interview_score(out of 10)  salary($)
0        NaN                    8.0                           9      50000
1        NaN                    8.0                           6      45000
2       five                    6.0                           7      60000
3        two                   10.0                          10      65000
4      seven                    9.0                           6      70000
5      three                    7.0                          10      62000
6        ten                    NaN                           7      72000
7     eleven                    7.0                           8      80000

## Data cleaning

In [36]:
df['experience']=df['experience'].fillna('zero')
df['test_score(out of 10)']=df['test_score(out of 10)'].fillna(round(df['test_score(out of 10)'].mean(),2))
df

experience  test_score(out of 10)  interview_score(out of 10)  salary($)
0       zero                   8.00                           9      50000
1       zero                   8.00                           6      45000
2       five                   6.00                           7      60000
3        two                  10.00                          10      65000
4      seven                   9.00                           6      70000
5      three                   7.00                          10      62000
6        ten                   7.86                           7      72000
7     eleven                   7.00                           8      80000

## Converting word to number in 'experience' column

In [19]:
!pip install word2number

  Created wheel for word2number: filename=word2number-1.1-py3-none-any.whl size=5580 sha256=097a7a7ecfb6cb6103b386784e55376fe4ac1e37a099bd6d3217daa929df2250
  Stored in directory: c:\users\user\appdata\local\pip\cache\wheels\a0\4a\5b\d2f2df5c344ddbecb8bea759872c207ea91d93f57fb54e816e
Successfully built word2number


In [39]:
from word2number import w2n
df['experience']=df['experience'].apply(w2n.word_to_num)
df

experience  test_score(out of 10)  interview_score(out of 10)  salary($)
0           0                   8.00                           9      50000
1           0                   8.00                           6      45000
2           5                   6.00                           7      60000
3           2                  10.00                          10      65000
4           7                   9.00                           6      70000
5           3                   7.00                          10      62000
6          10                   7.86                           7      72000
7          11                   7.00                           8      80000

## Training model

In [40]:
from sklearn.linear_model import LinearRegression
model=LinearRegression()
model.fit(df.drop('salary($)',axis=1),df['salary($)'])

LinearRegression()

In [41]:
model.predict([[2,9,6]])

array([53289.2205768])

In [42]:
model.predict([[12,10,10]])

array([92262.76628062])